import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:io';

// To run this script, execute: dart run lib/utils/firestore_seed.dart
// Ensure your Firebase configuration files (google-services.json and GoogleService-Info.plist)
// are in place and you have initialized the project with `flutterfire configure`.

Future<void> main() async {
  // This is a workaround to initialize Firebase in a standalone Dart script.
  // You must have a `firebase_options.dart` file generated by FlutterFire.
  // This script assumes it's being run from the root of your Flutter project.
  try {
    await Firebase.initializeApp();
  } catch (e) {
    print('Error initializing Firebase. Make sure you are in the project root and have run "flutterfire configure".');
    print('If that does not work, you may need to pass options manually.');
    // Example of manual initialization if the above fails:
    // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    exit(1);
  }

  print('Firebase Initialized. Seeding data...');

  final firestore = FirebaseFirestore.instance;
  final batch = firestore.batch();

  for (int i = 1; i <= 40; i++) {
    final docRef = firestore.collection('rooms').doc('room_$i');
    batch.set(docRef, {
      'room_id': i.toString(),
      'patient_id': null,
      'status': 'cleaned', // All rooms start as 'cleaned'
      'entry_time': null,
      'surgery_depart_time': null,
      'surgery_return_time': null,
      'discharge_time': null,
      'clean_time': DateTime.now().toIso8601String(),
      'mda_seen': false,
      'apass_seen': false,
      'preop_seen': false,
      'is_first_case': false,
      'is_ready': false,
      'prep_time_minutes': 0,
      // Add new fields with null defaults
      'assigned_nurse': null,
      'procedure_type': null,
      'surgeon_name': null,
    });
  }

  await batch.commit();
  print('Successfully seeded 40 rooms in Firestore.');
  // Exit the script once done.
  exit(0);
}
